name: 'Arduino sketch.json parser'
description: 'Action for parsing Arduino sketch.json file'
author: 'Nikolay Bely'
branding:
  icon: 'file-text'
  color: 'green'
inputs:
  sketchjson:
    description: 'sketch.json file location'
    required: false
    default: 'sketch.json'
outputs:
  platform:
    description: 'Platform string'
  fqbn:
    description: 'FQBN string'
  included_libs:
    description: 'Comma separated list of libraries'
runs:
  using: 'node12'
  main: 'dist/index.js'
